# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4, verbose_name='\u5b9a\u91d1\u6bd4\u7387'),
        ),
    ]
