# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-19 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': '\u7701/\u5e02/\u533a(\u53bf)', 'verbose_name_plural': '\u7701/\u5e02/\u533a(\u53bf)'},
        ),
    ]
